// Maps image files onto catalog records by filename, so each flavor gets its
// own picture rather than a shared placeholder.
//
// Usage: node scripts/link-images.mjs
//
// Drop files into public/assets/flavors/ named after the flavor id, e.g.
//   public/assets/flavors/brown-butter-pecan.webp
//   public/assets/flavors/meyer-lemon-cream.jpg
// Extension does not matter; the id before the extension is what is matched.
// Re-run after adding files. Output: src/image-manifest.js
//
// Unmatched files and flavors without an image are both reported, so a typo in
// a filename surfaces here instead of silently falling back to a placeholder.

import { readdir, writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

const SRC_DIR = path.resolve("public/assets/flavors");
const OUT_FILE = path.resolve("src/image-manifest.js");
const EXTS = /\.(webp|avif|jpe?g|png)$/i;

async function loadFlavorIds() {
  const mod = await import(pathToFileURL(path.resolve("src/catalog.js")).href);
  return mod.FLAVORS.map((f) => f.id);
}

async function main() {
  if (!existsSync(SRC_DIR)) {
    await mkdir(SRC_DIR, { recursive: true });
    console.log(`Created ${SRC_DIR}`);
  }

  const ids = await loadFlavorIds();
  const files = (await readdir(SRC_DIR)).filter((f) => EXTS.test(f));

  const manifest = {};
  const unmatched = [];

  for (const file of files) {
    const id = file.replace(EXTS, "");
    if (ids.includes(id)) manifest[id] = `/assets/flavors/${file}`;
    else unmatched.push(file);
  }

  const missing = ids.filter((id) => !manifest[id]);

  const body = `// GENERATED by scripts/link-images.mjs — do not edit by hand.
// Maps flavor id to its image path. Flavors absent from this map fall back to
// the CSS placeholder in styles.css.
export const IMAGES = ${JSON.stringify(manifest, null, 2)};
`;
  await writeFile(OUT_FILE, body);

  console.log(`Linked ${Object.keys(manifest).length}/${ids.length} flavors -> ${OUT_FILE}`);
  if (missing.length) {
    console.log(`\nStill on placeholders (${missing.length}):`);
    missing.forEach((id) => console.log(`  ${id}`));
  }
  if (unmatched.length) {
    console.log(`\nFiles matching no flavor id (${unmatched.length}):`);
    unmatched.forEach((f) => console.log(`  ${f}`));
    console.log(`\nValid ids: ${ids.join(", ")}`);
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
